spring.application.name=ecommerce-app
# spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.url=jdbc:mysql://mysql-351767ec-ecommerce-project.i.aivencloud.com:23242/defaultdb?ssl-mode=REQUIRED
# spring.datasource.username=root
spring.datasource.username=avnadmin
# spring.datasource.password=Shubham@410504
spring.datasource.password=AVNS_8XIN54ABiUGZx5htr7a

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect